SimpleStudentElections/Controllers/AdminElectionsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Helpers;
using System.Web.Mvc;
using AutoMapper;
using Hangfire;
using JetBrains.Annotations;
using Microsoft.AspNet.Identity;
using SimpleStudentElections.Auth;
using SimpleStudentElections.Helpers;
using SimpleStudentElections.Logic;
using SimpleStudentElections.Logic.ElectionMaintenanceJobs;
using SimpleStudentElections.Logic.Emails;
using SimpleStudentElections.Models;
using SimpleStudentElections.Models.Forms;

namespace SimpleStudentElections.Controllers
{
    /// <summary>
    /// This controller holds all admin actions except for the eligibility debugger
    /// </summary>
    [Authorize(Roles = Roles.StudentSupport)]
    public class AdminElectionsController : Controller
    {
        private readonly VotingDbContext db = new VotingDbContext();

        public ActionResult Current()
        {
            IList<Election> elections = db.Elections
                .Where(election => !ElectionLifecycleInfo.ArchivedStates.Contains(election.State))
                .ToList();

            return View(elections);
        }

        public ActionResult Details(int id)
        {
            Election election = db.Elections.Find(id);
            if (election == null) return HttpNotFound();

            DetailsData data = new DetailsData
            {
                Common = election,
                NomineeEntries = new NomineeFetcher(new TimetableUserRepository()).Fetch(election.Positions)
            };

            if (election.Type == ElectionType.StudentCouncil)
            {
                data.CouncilElectionData = db.CouncilElectionData
                    .First(councilData => councilData.ElectionId == id);
            }

            // ReSharper disable once SwitchStatementMissingSomeCases
            switch (election.State)
            {
                case ElectionState.Disabled:
                {
                    DetailsData.Action action = new DetailsData.Action()
                    {
                        Title = "Activate",
                        Url = Url.Action("Activate", new {id}),
                        CssType = "success"
                    };

                    SimpleValidationResult validationResult = ElectionLifecycleInfo.CanActivate(election);

                    if (!validationResult.IsNoErrors())
                    {
                        action.Enabled = false;
                        action.Tooltip = validationResult.Violations[0].HumanError;
                    }
                    else
                    {
                        action.Enabled = true;
                    }

                    data.Actions.Add(action);
                    break;
                }

                case ElectionState.PreNominations:
                {
                    DetailsData.Action action = new DetailsData.Action()
                    {
                        Title = "Deactivate",
                        Url = Url.Action("Deactivate", new {id}),
                        CssType = "warning",
                        Enabled = true,
                        Tooltip = "Go back to deactivated state"
                    };

                    data.Actions.Add(action);
                    break;
                }

                case ElectionState.Closed:
                {
                    DetailsData.Action action = new DetailsData.Action()
                    {
                        Title = "Publish results",
                        Url = Url.Action("PublishResults", new {id}),
                        CssType = "success",
                        Enabled = true
                    };

                    data.Actions.Add(action);
                    break;
                }
            }

            if (election.State == ElectionState.Aborted)
            {
                data.Actions.Add(new DetailsData.Action()
                {
                    Title = "Remove from system",
                    Enabled = true,
                    Url = Url.Action("Delete", new {id}),
                    CssType = "danger",
                });
            }
            else
            {
                if (ElectionLifecycleInfo.CanEdit(election))
                {
                    data.Actions.Add(new DetailsData.Action()
                    {
                        Title = "Edit",
                        Enabled = true,
                        Url = Url.Action("Edit", new {id}),
                        CssType = "primary"
                    });
                }

                // Should be last
                data.Actions.Add(new DetailsData.Action()
                {
                    Title = "Abort",
                    Enabled = true,
                    Url = Url.Action("Abort", new {id}),
                    CssType = "danger"
                });
            }

            return View(data);
        }

        public ActionResult SelectNewType()
        {
            // This is just a static template
            return View();
        }

        public ActionResult NewCouncil(int numRoles = 6)
        {
            ViewData[FormConstants.FieldsInfoKey] = NewCouncilFieldsInfo;
            CouncilElectionForm form = new CouncilElectionForm
            {
                Roles = DefaultCouncilRoles
                    .GenerateRoles(numRoles)
                    .Select(role => new CouncilRoleForm() {Name = role})
                    .ToList()
            };

            return View(form);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewCouncil(CouncilElectionForm form)
        {
            ModelFieldsAccessibility fieldsInfo = NewCouncilFieldsInfo;

            // Ignore stuff that isn't supposed to be in new election
            fieldsInfo.ReplaceUneditableWithOldValues(form, new CouncilElectionForm());
            this.RemoveIgnoredErrors(fieldsInfo);

            if (ModelState.IsValid)
            {
                Election election = Mapper.Map<Election>(form);
                election.Type = ElectionType.StudentCouncil;

                CouncilElectionData councilData = Mapper.Map<CouncilElectionData>(form);
                councilData.Election = election;

                ElectionStateChange createChangeInfo = new ElectionStateChange
                {
                    Election = election,
                    PreviousState = null,
                    TargetState = election.State,
                    IsCausedByUser = true,
                    InstigatorUsername = User.Identity.GetUserId(),
                    CompletedAt = DateTime.Now
                };

                db.Elections.Add(election);
                db.CouncilElectionData.Add(councilData);
                db.ElectionStateChanges.Add(createChangeInfo);

                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    db.SaveChanges();

                    // This needs to be after the first big transaction - otherwise EF gets confused about order of actions 
                    election.PopulateAutomaticStateTransitions();
                    db.SaveChanges();

                    transaction.Commit();
                }

                AuditLogManager.RecordNewElection(createChangeInfo);

                return RedirectToAction("Details", new {id = election.Id});
            }

            ViewData[FormConstants.FieldsInfoKey] = fieldsInfo;

            return View(form);
        }

        private static ModelFieldsAccessibility NewCouncilFieldsInfo
        {
            get
            {
                ModelFieldsAccessibility fieldsInfo =
                    CouncilElectionForm.DefaultCouncilFieldsInfo(ModelFieldsAccessibility.Kind.Editable);

                if (!ElectionLifecycleInfo.ShowResultsAdmin(null))
                {
                    fieldsInfo.MarkNotShown(nameof(ElectionForm.ResultsText));
                }

                return fieldsInfo;
            }
        }

        [HttpGet]
        public ActionResult NewCourseRep()
        {
            ViewData[FormConstants.FieldsInfoKey] = NewDefaultFieldsInfo;

            return View(new ElectionForm());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewCourseRep(ElectionForm form)
        {
            ModelFieldsAccessibility fieldsInfo = NewDefaultFieldsInfo;

            // Ignore stuff that isn't supposed to be in new election
            fieldsInfo.ReplaceUneditableWithOldValues(form, new ElectionForm());
            this.RemoveIgnoredErrors(fieldsInfo);

            if (ModelState.IsValid)
            {
                Election election = Mapper.Map<Election>(form);
                election.Type = ElectionType.CourseRepresentative;
                election.PositionGenerationInProcess = true;

                ElectionStateChange createChangeInfo = new ElectionStateChange
                {
                    Election = election,
                    PreviousState = null,
                    TargetState = election.State,
                    IsCausedByUser = true,
                    InstigatorUsername = User.Identity.GetUserId(),
                    CompletedAt = DateTime.Now
                };

                db.Elections.Add(election);
                db.ElectionStateChanges.Add(createChangeInfo);

                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    db.SaveChanges();

                    // This needs to be after the first big transaction - otherwise EF gets confused about order of actions 
                    election.PopulateAutomaticStateTransitions();
                    db.SaveChanges();

                    transaction.Commit();
                }

                AuditLogManager.RecordNewElection(createChangeInfo);

SimpleStudentElections/Views/AdminElections/Abort.cshtml
@using SimpleStudentElections.Logic
@model SimpleStudentElections.Models.Election

@{
    ViewBag.Title = Model.Name + " | Abortion";
}

<h2>@Model.Name</h2>

<div class="alert alert-danger">
    <div class="row">
        <div class="col-md-1">
            <i class="fas fa-exclamation-circle fa-4x"></i>
        </div>
        <div class="col-md-11">
            <h4 class="alert-heading">You are about to abort this election</h4>
            <p>
                This action will put the election into <strong>Aborted</strong> state.
                This means that this election will be scrapped forever
            </p>
            <hr/>
            <ul>
                <li>
                    This is a <strong>destructive and irreversible action</strong>. <strong>It cannot be undone</strong>!
                </li>
                <li>
                    The election and all associated data will remain in the system for at least @ElectionLifecycleInfo.GetConfiguration().MinDaysForDeletion days,
                    after which it can be manually removed
                </li>
            </ul>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <a href="@Url.Action("Details", new {id = Model.Id})" class="btn btn-secondary">Cancel</a>
        <button type="submit" class="btn btn-danger">Confirm</button>
    </div>
}

SimpleStudentElections/Views/AdminElections/Activate.cshtml
@model SimpleStudentElections.Models.Election

@{
    ViewBag.Title = Model.Name + " | Activation";
}

<h2>@Model.Name</h2>

<div class="alert alert-success">
    <h4 class="alert-heading">You are about to activate this election</h4>
    <p>
        This action will put the election into <strong>PreNominations</strong> state.
        This means:
        <ul>
            <li>Eligible students will be able to see this election in "upcoming elections" section</li>
            <li>
                When the time comes for nominations to begin the system will send emails to all elidgeble students
                and open the nominations (and generally proceed with normal schedule).
            </li>
        </ul>
    </p>
    <hr/>
    <ul>
        <li>You can only preform this action if at least a day remains until nominations start</li>
        <li>You can revert the election back to disabled state until the elections start</li>
    </ul>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <a href="@Url.Action("Details", new {id = Model.Id})" class="btn btn-danger">Cancel</a>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </div>
}

SimpleStudentElections/Views/AdminElections/Archived.cshtml
@using SimpleStudentElections.Models
@model ICollection<SimpleStudentElections.Models.Election>

@{
    ViewBag.Title = "Archived elections";
    ViewBag.HeaderMenuActive = "Archived";
}

<h2>Archived elections</h2>

<ul>
    @foreach (Election election in Model)
    {
        <li>
            <a href="@Url.Action("Details", new {id = election.Id})">@election.Name</a>
            @if (election.State == ElectionState.Aborted)
            {
                <text>(aborted)</text>
            }
        </li>
    }
</ul>

SimpleStudentElections/Views/AdminElections/Current.cshtml
@using SimpleStudentElections.Logic
@model IList<SimpleStudentElections.Models.Election>

@{
    ViewBag.Title = "Current elections";
    ViewBag.HeaderMenuActive = "Current";

    int numElections = Model.Count;
    int lastElection = numElections - 1;
}

<h2>Current elections</h2>

@if (numElections > 0)
{
    for (int i = 0; i < numElections; i++)
    {
        <div>
            <div class="d-flex justify-content-between">
                <h4>@Html.DisplayFor(m => m[i].Name)</h4>

                <div>
                    <a href="@Url.Action("Details", new {id = Model[i].Id})" class="btn btn-primary">Details and management</a>
                </div>
            </div>

            <div class="row" style="margin-top: 10px">
                <div class="col">
                    @{
                        Html.RenderPartial("_ElectionGeneralInfo", Model[i]);
                    }
                </div>

                <div class="col">
                    @Html.DisplayFor(m => m[i].Nominations, new
                    {
                        PhaseTitle = "Nominations phase",
                        ShowAlmostOver = ElectionLifecycleInfo.AreAlmostOverEmailsEnabled(Model[i])
                    })
                </div>

                <div class="col">
                    @Html.DisplayFor(m => m[i].Voting,new
                    {
                        PhaseTitle = "Voting phase",
                        ShowAlmostOver = ElectionLifecycleInfo.AreAlmostOverEmailsEnabled(Model[i])
                    })
                </div>
            </div>

            <div>
                <table class="table table-bordered table-sm">
                    <thead>
                    <tr>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>@Html.Raw(Model[i].Description)</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        if (i != lastElection)
        {
            <hr/>
        }
    }
}
else
{
    <div>There are currently no elections</div>
}

SimpleStudentElections/Views/AdminElections/Deactivate.cshtml
@model SimpleStudentElections.Models.Election

@{
    ViewBag.Title = Model.Name + " | Deativation";
}

<h2>@Model.Name</h2>

<div class="alert alert-warning">
    <h4 class="alert-heading">You are about to deactivate this election</h4>
    <p>
        This action will put the election into <strong>Disabled</strong> state.
        This means that nominations will not start and no emails will be sent until the election is activated again
    </p>
    <hr />
    <ul>
        <li>You can only preform this action at any time until nominations start</li>
        <li>You will be able to activate the election again if at least a day remains until nominations start</li>
    </ul>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div>
        <a href="@Url.Action("Details", new { id = Model.Id })" class="btn btn-danger">Cancel</a>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </div>
}

SimpleStudentElections/Views/AdminElections/Details.cshtml
@using SimpleStudentElections.Controllers
@using SimpleStudentElections.Logic
@using SimpleStudentElections.Models
@model SimpleStudentElections.Controllers.AdminElectionsController.DetailsData

@functions
{
    private class EmailDisplayData
    {
        public readonly string Title;
        public readonly EmailDefinition Definition;

        public EmailDisplayData(string title, EmailDefinition definition)
        {
            Title = title;
            Definition = definition;
        }
    }
}

@{
    ViewBag.Title = Model.Common.Name + " | Details";

    // ReSharper disable once UseObjectOrCollectionInitializer
    List<EmailDisplayData> emails = new List<EmailDisplayData>();

    emails.Add(new EmailDisplayData("Nominations started", Model.Common.NominationsStartedEmail));

    if (Model.Common.Type == ElectionType.StudentCouncil)
    {
        emails.Add(new EmailDisplayData(
            "Nominations almost over",
            Model.CouncilElectionData.NominationsAlmostOverEmail
        ));
    }

    emails.Add(new EmailDisplayData("Post nominations", Model.Common.PostNominationsEmail));

    if (Model.Common.Type == ElectionType.StudentCouncil)
    {
        emails.Add(new EmailDisplayData(
            "Voting started",
            Model.CouncilElectionData.VotingStartedEmail
        ));
        
        emails.Add(new EmailDisplayData(
            "Voting almost over",
            Model.CouncilElectionData.VotingAlmostOverEmail
        ));
    }

    emails.Add(new EmailDisplayData("Post voting", Model.Common.PostVotingEmail));
    emails.Add(new EmailDisplayData("Results published", Model.Common.ResultsPublishedEmail));
}

<div class="d-flex justify-content-between">
    <h2>@Model.Common.Name</h2>

    <div>
        @foreach (AdminElectionsController.DetailsData.Action action in Model.Actions)
        {
            TagBuilder tag = new TagBuilder(action.Enabled ? "a" : "button");

            tag.AddCssClass("btn");
            tag.AddCssClass("btn-" + action.CssType);
            tag.InnerHtml = action.Title;
            tag.Attributes["type"] = "button";

            if (action.Enabled)
            {
                tag.Attributes["href"] = action.Url;
            }
            else
            {
                tag.Attributes["disabled"] = "disabled";
            }

            if (action.Tooltip != null)
            {
                tag.Attributes["data-toggle"] = "tooltip";
                tag.Attributes["title"] = action.Tooltip;
            }

            @Html.Raw(tag)

            // This is required for space between buttons ¯\_(ツ)_/¯
            <text></text>
        }
    </div>
</div>

<div class="row" style="margin-top: 10px">
    <div class="col">
        @{
            Html.RenderPartial("_ElectionGeneralInfo", Model.Common);
        }
    </div>

    <div class="col">
        @Html.DisplayFor(m => m.Common.Nominations, new
        {
            PhaseTitle = "Nominations phase",
            ShowAlmostOver = ElectionLifecycleInfo.AreAlmostOverEmailsEnabled(Model.Common)
        })
    </div>

    <div class="col">
        @Html.DisplayFor(m => m.Common.Voting, new
        {
            PhaseTitle = "Voting phase",
            ShowAlmostOver = ElectionLifecycleInfo.AreAlmostOverEmailsEnabled(Model.Common)
        })
    </div>
</div>

<div class="accordion" id="desc-accordion">
    <div class="card">
        <div class="card-header py-0">
            <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#desc-collapse" aria-expanded="true" aria-controls="desc-collapse">
                    @Html.DisplayNameFor(m => m.Common.Description)
                </button>
            </h5>
        </div>

        <div id="desc-collapse" class="collapse show" data-parent="#desc-accordion">
            <div class="card-body">
                @Html.Raw(Model.Common.Description)
            </div>
        </div>
    </div>
    
    @if (ElectionLifecycleInfo.ShowResultsAdmin(Model.Common))
    {
        <div class="card">
            <div class="card-header py-0">
                <h5 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#results-collapse" aria-expanded="true" aria-controls="results-collapse">
                        Results
                    </button>
                </h5>
            </div>

            <div id="results-collapse" class="collapse" data-parent="#desc-accordion">
                <div class="card-body">
                    @Html.Raw(Model.Common.ResultsText)
                </div>
            </div>
        </div>
    }

    <div class="card">
        <div class="card-header py-0">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#positions-collapse" aria-expanded="false" aria-controls="positions-collapse">
                    @Html.DisplayNameFor(m => m.Common.Positions)
                </button>
            </h5>
        </div>
        <div id="positions-collapse" class="collapse" data-parent="#desc-accordion">
            <div class="card-body d-flex justify-content-between">
                @if (Model.Common.PositionGenerationInProcess)
                {
                    <p class="text-muted">Position generation in process</p>
                }
                else
                {
                    <ul class="mb-0">
                        @foreach (VotablePosition position in Model.Common.PositionsSorted)
                        {
                            <li>
                                @position.HumanName
                            </li>
                        }
                    </ul>

                    if (ElectionLifecycleInfo.CanForcePositionGeneration(Model.Common))
                    {
                        <div>
                            <form method="post" action="@Url.Action("RegeneratePositions")" class="d-inline">
                                <button type="submit" class="btn btn-primary">Regenerate positions</button>
                            </form>
                        </div>
                    }
                }
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header py-0">
            <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#nominations-collapse" aria-expanded="true" aria-controls="nominations-collapse">
                    Nominations
                </button>
            </h5>
        </div>

        <div id="nominations-collapse" class="collapse" data-parent="#desc-accordion">
            <div class="card-body">
                <p>
                    <strong>Status</strong>:
                    @if (Model.Common.State == ElectionState.Nominations)
                    {
                        <text>nominations are currently underway</text>
                    }
                    else if (ElectionLifecycleInfo.IsInactive(Model.Common))
                    {
                        <text>this election is inactive</text>
                    }
                    else if (ElectionLifecycleInfo.IsBefore(Model.Common, ElectionState.Nominations))
                    {
                        <text>
                            this election is in <strong>@Html.DisplayFor(m => m.Common.State)</strong> state - nominations haven't started yet
                        </text>
                    }
                    else if (ElectionLifecycleInfo.IsAfter(Model.Common, ElectionState.Nominations))
                    {
                        <text>
                            this election is in <strong>@Html.DisplayFor(m => m.Common.State)</strong> state - nominations have finished
                        </text>
                    }
                </p>

                <div>
                    <strong>Nominees</strong>:

                    <table class="table table-bordered">
                        @foreach (var position in Model.Common.Positions.OrderBy(p => p.Id))
                        {
                            <tr>
                                <td style="width: 25%">@position.HumanName</td>
                                <td>
                                    <ul style="padding-left: 20px; margin-bottom: 0">
                                        @foreach (DisplayNomineeEntry entry in Model.NomineeEntries[position])
                                        {
                                            <li>@Html.DisplayFor(m => entry)</li>
                                        }
                                    </ul>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card">
        <div class="card-header py-0">
            <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#votes-collapse" aria-expanded="true" aria-controls="votes-collapse">
                    Votes
                </button>
            </h5>
        </div>

        <div id="votes-collapse" class="collapse" data-parent="#desc-accordion">
            <div class="card-body">
                Note that viewing votes will be recorded. You can view the records under the "Audit" tab 
                <form method="post" action="@Url.Action("ViewVotes")">
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", Model.Common.Id)
                    <button class="btn btn-success">Proceed</button>
                </form>
            </div>
        </div>
    </div>
    
    <div class="card">
            <div class="card-header py-0">
                <h5 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#eligibility-collapse" aria-expanded="true" aria-controls="eligibility-collapse">
                        Eligibility
                    </button>
                </h5>
            </div>
    
            <div id="eligibility-collapse" class="collapse" data-parent="#desc-accordion">
                <div class="card-body">
                    <div>
                        <a href="@Url.Action("Election", "EligibilityDebugger", new {id = Model.Common.Id})" class="btn btn-success">
                            Election eligibility
                        </a>
                        <a href="@Url.Action("Positions", "EligibilityDebugger", new {electionId = Model.Common.Id})" class="btn btn-success">
                            Positions eligibility
                        </a>
                    </div>
                </div>
            </div>
        </div>
        
    <div class="card">
        <div class="card-header py-0">
            <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#audit-collapse" aria-expanded="true" aria-controls="audit-collapse">
                    Audit
                </button>
            </h5>
        </div>

        <div id="audit-collapse" class="collapse" data-parent="#desc-accordion">
            <div class="card-body">
                <div>
                    <a href="@Url.Action("EventLog",  new {id = Model.Common.Id})" class="btn btn-success">
                        Event log
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<h4 class="mt-4">Emails</h4>

<div class="accordion" id="emails-accordion">
    @for (int i = 0; i < emails.Count; i++)
    {
        <div class="card">
            <div class="card-header py-0">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#emails-@i" aria-expanded="true" aria-controls="emails-@i">
                        @emails[i].Title
                    </button>
                </h5>
            </div>

            <div id="emails-@i" class="collapse" data-parent="#emails-accordion">
                <div class="card-body">
                    @if (!emails[i].Definition.IsEnabled)
                    {
                        <span class="text-muted">This email is disabled</span>
                    }
                    else
                    {
                        <p>
                            <strong>Subject:</strong> @emails[i].Definition.Subject
                        </p>
                        
                        @Html.Raw(emails[i].Definition.Body)
                    }
                </div>
            </div>
        </div>
    }
</div>

@section scripts
{
    <script>
        $(function() {
            $('[data-toggle="tooltip"]').tooltip();
        })
    </script>
}

SimpleStudentElections/Views/AdminElections/Edit.cshtml
@using SimpleStudentElections.Helpers
@using SimpleStudentElections.Models
@model SimpleStudentElections.Models.Forms.ElectionForm

@{
    Election election = ViewBag.Election;

    ViewBag.Title = election.Name + " | Edit"; // Use non-edited name until changes are validated and saved

    Html.IncludeCkeditor();
}

<h2>Edit "@election.Name"</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.EditorForModel()

    <div class="form-group row">
        <div class="offset-md-2 col-md-10">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

SimpleStudentElections/Views/AdminElections/SelectNewType.cshtml
@model dynamic

@{
    ViewBag.Title = "Create new election";
    ViewBag.HeaderMenuActive = "New";
}

<h2>Please select election type</h2>

<div class="row">
    <div class="col">
        <div class="jumbotron">
            <h1>Student council</h1>
            <p class="lead">Available to all active students. You can name a set of roles to vote for. Everybody can vote for all roles</p>
            <p>
                @using (Html.BeginForm("NewCouncil", "AdminElections", FormMethod.Get, new {@class = "form-inline justify-content-end"}))
                {
                    <div class="input-group mu-2 mr-sm-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">Number of roles</div>
                        </div>
                        <input type="number" class="form-control" value="6" style="width: 80px" name="numRoles">
                    </div>

                    <button type="submit" class="btn btn-primary btn-lg">Create</button>
                }
            </p>
        </div>
    </div>

    <div class="col">
        <div class="jumbotron">
            <h1>Course representatives</h1>
            <p class="lead">Available to all active students. The election will be automatically segregated by course/year tuples</p>
            <p style="text-align: right">
                <a href="@Url.Action("NewCourseRep")" class="btn btn-primary btn-lg">Create</a>
            </p>
        </div>
    </div>
</div>